plugins:
  - uses:
      - plugin: "https://ubiquity-os-plugin-demo-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-start-stop-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-command-wallet-main.ubiquity.workers.dev"
  - uses:
      - plugin: "ubiquity-os-marketplace/command-ask@main"
  - uses:
      - plugin: "https://ubiquity-os-command-query-user-main.ubiquity.workers.dev"
  - uses:
      - plugin: "https://ubiquity-os-daemon-pricing-main.ubiquity.workers.dev"
        skipBotEvents: false
  - uses:
      - plugin: "ubiquity-os-marketplace/text-conversation-rewards@main"
        skipBotEvents: false
        with:
          incentives:
            collaboratorOnlyPaymentInvocation: false
            contentEvaluator: {}
            userExtractor: {}
            dataPurge: {}
            formattingEvaluator: {}
            permitGeneration: {}
            githubComment: {}
          evmPrivateEncrypted: "s4akyv_Ql0BSIbIp2nDYb4o6WDHoKJDEZlCik9RONRWRWh43EBuR0TxcOe5Ap0BD5rMg_PZQQKGEBEhFrq33gTo67F4B162HhegG9N7X3m9NGd9Kd7t806q87WxtdPsdTUd28-pEDCl65wF4YEfYc3b3yx7WnK91w_xNircFa36HdkP_"
          evmNetworkId: 100
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-disqualifier@main"
  - uses:
      - plugin: "ubiquity-os-marketplace/daemon-merging@main"
  - uses:
      - plugin: "https://ubiquity-os-comment-vector-embeddings-main.ubiquity.workers.dev"
